# Generated by Django 3.2.7 on 2021-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('LM', 'Lengua Materna'), ('DM', 'Desafíos Matemáticos'), ('CN', 'Ciencias Naturales'), ('ECE', 'Educación cívica y ética'), ('J', 'Jalisco'), ('EF', 'Educación física')], default='LM', max_length=3)),
            ],
        ),
    ]
