# Generated by Django 3.2.7 on 2021-10-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='materia',
            field=models.CharField(choices=[('LM', 'Lengua Materna'), ('DM', 'Desafíos Matemáticos'), ('CN', 'Ciencias Naturales'), ('ECE', 'Educación cívica y ética'), ('J', 'Jalisco'), ('EF', 'Educación física')], default='LM', max_length=3),
        ),
    ]
