# Generated by Django 3.2.7 on 2021-10-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fechaLimite', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='tareas_maestro/pdfs/')),
            ],
        ),
    ]
