# Generated by Django 3.2.7 on 2021-10-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_tarea', '0003_rename_archivo_filesupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='fechaLimite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesupload',
            name='tema',
            field=models.CharField(default='Tarea', max_length=45),
        ),
    ]
