# Generated by Django 3.2.7 on 2021-10-13 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_tarea', '0004_auto_20211012_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
