# Generated by Django 3.2.7 on 2021-10-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_tarea', '0005_alter_filesupload_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='tema',
            field=models.CharField(max_length=45),
        ),
    ]
