# Generated by Django 3.2.7 on 2021-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_tarea', '0006_alter_filesupload_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='tema',
            field=models.CharField(default='Tarea', max_length=45),
        ),
    ]
