# Generated by Django 3.2.7 on 2021-10-13 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_tarea', '0007_alter_filesupload_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('tema', models.CharField(default='Tarea', max_length=45)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fechaLimite', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
