# Generated by Django 3.2.7 on 2021-10-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_account_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
    ]
